# Nome da aplicacao
spring.application.name=supermercado

# Porta fornecida pelo Railway
server.port=${PORT:8080}

# Banco de dados MySQL
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://switchyard.proxy.rlwy.net:25138/railway?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${JDBC_DATABASE_USERNAME:root}
spring.datasource.password=${JDBC_DATABASE_PASSWORD:pOmRGhpNpXzBzhAMTFctBdTaUmvBmmYU}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracoes JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Formatacao e logging (opcional)
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
